service: commcare-connect

image: commcare-connect

healthcheck:
  path: /
  port: 8000
  max_attempts: 20
  interval: 20s

ssh:
  user: connect
  proxy_command: "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"

logging:
  driver: awslogs
  options:
    awslogs-region: 'us-east-1'

builder:
  multiarch: false
  dockerfile: '../Dockerfile'
  context: '../'

registry:
  server: 037129986032.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(./registry_password.sh) %>
