webservers:
  hosts:
    web0:
      ansible_host: 52.70.100.12
    web1:
      ansible_host: 54.211.180.233
    celery0:
      ansible_host: 44.193.193.67
  vars:
    ansible_user: ubuntu
    secrets_file: 'Ansible Secrets - Production'
    commcare_hq_url: 'https://www.commcarehq.org'
    deploy_environment: 'production'
